const expectedRoot = [
  "ARTIFACT_PACKAGE_COMPATIBILITY",
  "ARTIFACT_PROTOCOL_COMPATIBILITY",
  "ARTIFACT_PROTOCOL_VERSION",
  "ApprovalEditor",
  "BREAKDOWN_PROTOCOL_VERSION",
  "BreakdownDocument",
  "BreakdownDocumentBuilder",
  "BreakdownEditor",
  "BreakdownEditorHistoryController",
  "ChallengeEditor",
  "CriteriaEditor",
  "DEFAULT_EDITOR_HISTORY_LIMIT",
  "DefinitionEditor",
  "DeliverableEditor",
  "DependencyEditor",
  "EvidenceEditor",
  "FixedBreakdownClock",
  "FixedMilestoneClock",
  "FixedTaskClock",
  "MAX_EDITOR_HISTORY_LIMIT",
  "MILESTONE_PROTOCOL_VERSION",
  "MilestoneDocument",
  "MilestoneDocumentBuilder",
  "MilestoneDomainError",
  "MilestoneEditor",
  "MilestoneEditorHistoryController",
  "MilestoneSourceEditor",
  "MilestoneValidationError",
  "ReviewEditor",
  "RevisionEditor",
  "SequenceBreakdownIdGenerator",
  "SequenceMilestoneIdGenerator",
  "SequenceTaskIdGenerator",
  "SourceEditor",
  "SystemBreakdownClock",
  "SystemMilestoneClock",
  "SystemTaskClock",
  "TASK_PROTOCOL_VERSION",
  "TaskDocument",
  "TaskDocumentBuilder",
  "TaskEditor",
  "TaskEditorHistoryController",
  "affectedMilestoneIds",
  "asAcceptanceId",
  "asApprovalRecordId",
  "asApprovalStageId",
  "asBreakdownEventId",
  "asBreakdownId",
  "asChallengeEvidenceId",
  "asChallengeId",
  "asCompletionId",
  "asCriterionId",
  "asDeliverableRequirementId",
  "asDependencyId",
  "asMilestoneEventId",
  "asMilestoneId",
  "asMilestoneProfileId",
  "asMilestoneRevisionId",
  "asReviewId",
  "asTaskEventId",
  "asTaskId",
  "asTaskProfileId",
  "asTaskReminderId",
  "asTaskRevisionId",
  "assertValidBreakdown",
  "assertValidBreakdownHierarchy",
  "assertValidGraph",
  "assertValidMilestone",
  "assertValidSourceLink",
  "assertValidTask",
  "assertValidTaskGraph",
  "assertValidTaskScopeGraph",
  "blockedMilestoneIds",
  "calculateProgress",
  "calculateTaskProgress",
  "createBreakdownDocument",
  "createBreakdownDocumentContext",
  "createGraphSnapshot",
  "createMilestoneDocument",
  "createMilestoneDocumentContext",
  "createTaskDocument",
  "createTaskDocumentContext",
  "createTaskGraphSnapshot",
  "defaultEvaluationPolicy",
  "defaultTaskEvaluationPolicy",
  "deriveMilestoneState",
  "deriveTaskState",
  "deserializeArtifactContext",
  "deserializeBreakdown",
  "deserializeBreakdownEvents",
  "deserializeBreakdownJson",
  "deserializeEvents",
  "deserializeGraph",
  "deserializeMilestone",
  "deserializeMilestoneJson",
  "deserializeTask",
  "deserializeTaskEvents",
  "deserializeTaskGraph",
  "deserializeTaskJson",
  "detectBreakdownCycles",
  "detectCycles",
  "detectTaskGraphCycles",
  "detectTaskScopeCycles",
  "downstreamImpact",
  "evaluateAcceptance",
  "evaluateArtifacts",
  "evaluateCompletion",
  "evaluateDependency",
  "evaluateGraph",
  "evaluateTaskAcceptance",
  "evaluateTaskCompletion",
  "evaluateTaskDependencies",
  "evaluateTaskDependency",
  "findUnlockedMilestoneIds",
  "graphNodeFromTask",
  "isDefinitionBearing",
  "migrateAndDeserializeBreakdown",
  "migrateAndDeserializeMilestone",
  "migrateAndDeserializeTask",
  "migrateBreakdownWire",
  "migrateMilestoneWire",
  "migrateTaskWire",
  "readyMilestoneIds",
  "resolveChallengeEvidenceSources",
  "resolveSourceLink",
  "resolveSources",
  "serializeArtifactContext",
  "serializeBreakdown",
  "serializeBreakdownEvents",
  "serializeBreakdownJson",
  "serializeEvents",
  "serializeGraph",
  "serializeMilestone",
  "serializeMilestoneJson",
  "serializeTask",
  "serializeTaskEvents",
  "serializeTaskGraph",
  "serializeTaskJson",
  "sourceLinksForRevision",
  "validateBreakdown",
  "validateBreakdownHierarchy",
  "validateGraph",
  "validateMilestone",
  "validateTask",
  "validateTaskGraph",
  "validateTaskScopeGraph",
].sort();

const pkg = await import("../dist/index.js");
const actualRoot = Object.keys(pkg).sort();
if (JSON.stringify(actualRoot) !== JSON.stringify(expectedRoot)) {
  throw new Error(`Root export snapshot changed:\n${actualRoot.join("\n")}`);
}
if (pkg.ARTIFACT_PROTOCOL_COMPATIBILITY !== ">=1.1 <2.0") throw new Error("Artifact protocol compatibility mismatch");

const subpaths = {
  model: "MilestoneDomainError",
  evaluation: "evaluateAcceptance",
  graph: "createGraphSnapshot",
  serialization: "serializeMilestone",
  validation: "validateMilestone",
  testing: "FixedMilestoneClock",
  migrations: "migrateMilestoneWire",
  dom: "MilestoneDocument",
};
for (const [subpath, requiredExport] of Object.entries(subpaths)) {
  const module = await import(`../dist/public/${subpath}.js`);
  if (!(requiredExport in module)) throw new Error(`${subpath} is missing ${requiredExport}`);
}

for (const internalName of ["invariant", "graphNodeFromMilestone", "validateProfile", "validateRevisionSnapshot"]) {
  if (internalName in pkg) throw new Error(`Internal helper ${internalName} leaked from the root API`);
}

console.log(`exports verified (${actualRoot.length} curated root exports, ${Object.keys(subpaths).length} subpaths)`);
